# @package experiment.config.step_hook
_target_: tbp.teleop.aggregate.Aggregator
observations:
  _target_: tbp.teleop.aggregate.SmartObservationAggregator
consumer:
  _target_: tbp.teleop.wire.FramePublisher
  endpoint: tcp://127.0.0.1:5555
