# @package experiment.config.step_hook
_target_: tbp.teleop.aggregate.Aggregator
observations:
  _target_: tbp.teleop.aggregate.observations.SmartObservationAggregator
actions:
  _target_: tbp.teleop.aggregate.actions.DefaultActionAggregator
experiment:
  _target_: tbp.teleop.aggregate.experiment.DefaultExperimentAggregator
consumer:
  _target_: tbp.teleop.recording.FrameWriter
  save_path: run.frames
