# @package experiment.config.step_hook
_target_: tbp.teleop.aggregate.Aggregator
observations:
  _target_: tbp.teleop.aggregate.SmartObservationAggregator
consumer:
  _target_: tbp.teleop.recording.FrameWriter
  save_path: run.frames
